theme = "kanagawa"

[editor]
color-modes = true
popup-border = "menu"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
separator = " »"
left = ["mode", "spinner", "version-control", "separator", "file-name", "read-only-indicator", "file-modification-indicator"]
center = []
right = ["diagnostics", "file-encoding"]

[editor.file-picker]
hidden = false

[keys.normal]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
"C-]" = "goto_definition"

"C-g" = ":sh gh browse -n %{buffer_name} | pbcopy"
"C-q" = ":quit"
